//------------------------------------------------------------------------------
// <auto-generated>
//     Denna kod har genererats av ett verktyg.
//     Körtidsversion:4.0.30319.42000
//
//     Ändringar i denna fil kan orsaka fel och kommer att förloras om
//     koden återgenereras.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://minameddelanden.gov.se/schema/Common", ClrNamespace = "minameddelanden.gov.se.schema.Common")]
[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://minameddelanden.gov.se/schema/Common/v3", ClrNamespace = "minameddelanden.gov.se.schema.Common.v3")]



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Name = "MessagePort-v2", Namespace = "http://minameddelanden.gov.se/Message", ConfigurationName = "MessagePortv2")]
public interface MessagePortv2
{

    // CODEGEN: Meddelandekontrakt genereras eftersom omslutningsnamnområde (wrapper) (http://minameddelanden.gov.se/schema/Message/v2) i meddelande distributeSecureRequest inte matchar standardvärdet (http://minameddelanden.gov.se/Message)
    [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
    [System.ServiceModel.FaultContractAttribute(typeof(minameddelanden.gov.se.schema.Common.ExceptionInformation), Action = "", Name = "distributeSecureFault")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    distributeSecureResponse distributeSecure(distributeSecureRequest request);

    [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
    System.Threading.Tasks.Task<distributeSecureResponse> distributeSecureAsync(distributeSecureRequest request);

    // CODEGEN: Parameter return kräver ytterligare schemainformation som inte kan registreras i parameterläge. Det specifika attributet är System.Xml.Serialization.XmlElementAttribute.
    [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
    [System.ServiceModel.FaultContractAttribute(typeof(minameddelanden.gov.se.schema.Common.ExceptionInformation), Action = "", Name = "checkDistributionStatusFault")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [return: System.ServiceModel.MessageParameterAttribute(Name = "return")]
    checkDistributionStatusResponse checkDistributionStatus(checkDistributionStatusRequest request);

    [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
    System.Threading.Tasks.Task<checkDistributionStatusResponse> checkDistributionStatusAsync(checkDistributionStatusRequest request);
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://minameddelanden.gov.se/schema/Message/v2")]
public partial class SignedDelivery
{

    private SecureDelivery deliveryField;

    private SignatureType signatureField;

    private string idField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public SecureDelivery Delivery
    {
        get
        {
            return this.deliveryField;
        }
        set
        {
            this.deliveryField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://www.w3.org/2000/09/xmldsig#", Order = 1)]
    public SignatureType Signature
    {
        get
        {
            return this.signatureField;
        }
        set
        {
            this.signatureField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "ID")]
    public string Id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://minameddelanden.gov.se/schema/Message/v2")]
public partial class SecureDelivery
{

    private SecureDeliveryHeader headerField;

    private SecureMessage[] messageField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public SecureDeliveryHeader Header
    {
        get
        {
            return this.headerField;
        }
        set
        {
            this.headerField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Message", Order = 1)]
    public SecureMessage[] Message
    {
        get
        {
            return this.messageField;
        }
        set
        {
            this.messageField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://minameddelanden.gov.se/schema/Message/v2")]
public partial class SecureDeliveryHeader
{

    private Sender senderField;

    private string recipientField;

    private string referenceField;

    private string correlationIdField;

    private string attentionField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public Sender Sender
    {
        get
        {
            return this.senderField;
        }
        set
        {
            this.senderField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
    public string Recipient
    {
        get
        {
            return this.recipientField;
        }
        set
        {
            this.recipientField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
    public string Reference
    {
        get
        {
            return this.referenceField;
        }
        set
        {
            this.referenceField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
    public string CorrelationId
    {
        get
        {
            return this.correlationIdField;
        }
        set
        {
            this.correlationIdField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
    public string Attention
    {
        get
        {
            return this.attentionField;
        }
        set
        {
            this.attentionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://minameddelanden.gov.se/schema/Sender")]
public partial class Sender
{

    private string idField;

    private string nameField;

    private string attentionField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public string Id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
    public string Name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
    public string Attention
    {
        get
        {
            return this.attentionField;
        }
        set
        {
            this.attentionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://minameddelanden.gov.se/schema/OfficialMatter/v3")]
public partial class OfficialMatterExtension
{

    private System.DateTime timestampField;

    private System.Xml.XmlElement[] anyField;

    private OfficialMatterExtensionIdentity identityField;

    private string matterSubjectField;

    private string eventTypeField;

    private OfficialMatterExtensionMatterStatus matterStatusField;

    private bool matterStatusFieldSpecified;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "date", Order = 0)]
    public System.DateTime Timestamp
    {
        get
        {
            return this.timestampField;
        }
        set
        {
            this.timestampField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute(Order = 1)]
    public System.Xml.XmlElement[] Any
    {
        get
        {
            return this.anyField;
        }
        set
        {
            this.anyField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
    public OfficialMatterExtensionIdentity Identity
    {
        get
        {
            return this.identityField;
        }
        set
        {
            this.identityField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
    public string MatterSubject
    {
        get
        {
            return this.matterSubjectField;
        }
        set
        {
            this.matterSubjectField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
    public string EventType
    {
        get
        {
            return this.eventTypeField;
        }
        set
        {
            this.eventTypeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
    public OfficialMatterExtensionMatterStatus MatterStatus
    {
        get
        {
            return this.matterStatusField;
        }
        set
        {
            this.matterStatusField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool MatterStatusSpecified
    {
        get
        {
            return this.matterStatusFieldSpecified;
        }
        set
        {
            this.matterStatusFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://minameddelanden.gov.se/schema/OfficialMatter/v3")]
public partial class OfficialMatterExtensionIdentity
{

    private string eventIdField;

    private string officialMatterIdField;

    private string precedingEventIdField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public string EventId
    {
        get
        {
            return this.eventIdField;
        }
        set
        {
            this.eventIdField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
    public string OfficialMatterId
    {
        get
        {
            return this.officialMatterIdField;
        }
        set
        {
            this.officialMatterIdField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
    public string PrecedingEventId
    {
        get
        {
            return this.precedingEventIdField;
        }
        set
        {
            this.precedingEventIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://minameddelanden.gov.se/schema/OfficialMatter/v3")]
public enum OfficialMatterExtensionMatterStatus
{

    /// <remarks/>
    senderinitiative,

    /// <remarks/>
    recipientinitiative,

    /// <remarks/>
    closed,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://minameddelanden.gov.se/schema/Message/v3")]
public partial class OfficialMatter
{

    private object itemField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute(Order = 0)]
    [System.Xml.Serialization.XmlElementAttribute("OfficialMatterExtension", typeof(OfficialMatterExtension), Order = 0)]
    public object Item
    {
        get
        {
            return this.itemField;
        }
        set
        {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "SupportInfo", Namespace = "http://minameddelanden.gov.se/schema/Message/v3")]
public partial class SupportInfo1
{

    private string textField;

    private string uRLField;

    private string phoneNumberField;

    private string emailAdressField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public string Text
    {
        get
        {
            return this.textField;
        }
        set
        {
            this.textField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "anyURI", Order = 1)]
    public string URL
    {
        get
        {
            return this.uRLField;
        }
        set
        {
            this.uRLField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
    public string PhoneNumber
    {
        get
        {
            return this.phoneNumberField;
        }
        set
        {
            this.phoneNumberField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
    public string EmailAdress
    {
        get
        {
            return this.emailAdressField;
        }
        set
        {
            this.emailAdressField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "MessageHeader", Namespace = "http://minameddelanden.gov.se/schema/Message/v3")]
public partial class MessageHeader1
{

    private string idField;

    private string subjectField;

    private SupportInfo1 supportinfoField;

    private OfficialMatter officialMatterField;

    private MetaData[] metadataField;

    private string languageField;

    private ReplyOptions replyField;

    private bool replyFieldSpecified;

    private ReceiptOptions receiptRequestField;

    private bool receiptRequestFieldSpecified;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public string Id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
    public string Subject
    {
        get
        {
            return this.subjectField;
        }
        set
        {
            this.subjectField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
    public SupportInfo1 Supportinfo
    {
        get
        {
            return this.supportinfoField;
        }
        set
        {
            this.supportinfoField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
    public OfficialMatter OfficialMatter
    {
        get
        {
            return this.officialMatterField;
        }
        set
        {
            this.officialMatterField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Metadata", Order = 4)]
    public MetaData[] Metadata
    {
        get
        {
            return this.metadataField;
        }
        set
        {
            this.metadataField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "language", Order = 5)]
    public string Language
    {
        get
        {
            return this.languageField;
        }
        set
        {
            this.languageField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
    public ReplyOptions Reply
    {
        get
        {
            return this.replyField;
        }
        set
        {
            this.replyField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ReplySpecified
    {
        get
        {
            return this.replyFieldSpecified;
        }
        set
        {
            this.replyFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 7)]
    public ReceiptOptions ReceiptRequest
    {
        get
        {
            return this.receiptRequestField;
        }
        set
        {
            this.receiptRequestField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ReceiptRequestSpecified
    {
        get
        {
            return this.receiptRequestFieldSpecified;
        }
        set
        {
            this.receiptRequestFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://minameddelanden.gov.se/schema/Message")]
public partial class MetaData
{

    private string tagField;

    private string valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public string Tag
    {
        get
        {
            return this.tagField;
        }
        set
        {
            this.tagField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://minameddelanden.gov.se/schema/Reply")]
public enum ReplyOptions
{

    /// <remarks/>
    REQUESTED,

    /// <remarks/>
    ACCEPTED,

    /// <remarks/>
    NOT_ALLOWED,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://minameddelanden.gov.se/schema/Receipt")]
public enum ReceiptOptions
{

    /// <remarks/>
    NOT,

    /// <remarks/>
    SIMPLE,

    /// <remarks/>
    SIGNED,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "SecureMessage", Namespace = "http://minameddelanden.gov.se/schema/Message/v3")]
public partial class SecureMessage1
{

    private MessageHeader1 headerField;

    private MessageBody bodyField;

    private Attachment[] attachmentField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public MessageHeader1 Header
    {
        get
        {
            return this.headerField;
        }
        set
        {
            this.headerField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
    public MessageBody Body
    {
        get
        {
            return this.bodyField;
        }
        set
        {
            this.bodyField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Attachment", Order = 2)]
    public Attachment[] Attachment
    {
        get
        {
            return this.attachmentField;
        }
        set
        {
            this.attachmentField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://minameddelanden.gov.se/schema/Message")]
public partial class MessageBody
{

    private string contentTypeField;

    private byte[] bodyField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public string ContentType
    {
        get
        {
            return this.contentTypeField;
        }
        set
        {
            this.contentTypeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "base64Binary", Order = 1)]
    public byte[] Body
    {
        get
        {
            return this.bodyField;
        }
        set
        {
            this.bodyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://minameddelanden.gov.se/schema/Message")]
public partial class Attachment
{

    private string contentTypeField;

    private byte[] bodyField;

    private string checksumField;

    private string filenameField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public string ContentType
    {
        get
        {
            return this.contentTypeField;
        }
        set
        {
            this.contentTypeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "base64Binary", Order = 1)]
    public byte[] Body
    {
        get
        {
            return this.bodyField;
        }
        set
        {
            this.bodyField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
    public string Checksum
    {
        get
        {
            return this.checksumField;
        }
        set
        {
            this.checksumField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
    public string Filename
    {
        get
        {
            return this.filenameField;
        }
        set
        {
            this.filenameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "SecureDelivery", Namespace = "http://minameddelanden.gov.se/schema/Message/v3")]
public partial class SecureDelivery1
{

    private SecureDeliveryHeader headerField;

    private SecureMessage1[] messageField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public SecureDeliveryHeader Header
    {
        get
        {
            return this.headerField;
        }
        set
        {
            this.headerField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Message", Order = 1)]
    public SecureMessage1[] Message
    {
        get
        {
            return this.messageField;
        }
        set
        {
            this.messageField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "SignedDelivery", Namespace = "http://minameddelanden.gov.se/schema/Message/v3")]
public partial class SignedDelivery1
{

    private SecureDelivery1 deliveryField;

    private SignatureType signatureField;

    private string idField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public SecureDelivery1 Delivery
    {
        get
        {
            return this.deliveryField;
        }
        set
        {
            this.deliveryField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://www.w3.org/2000/09/xmldsig#", Order = 1)]
    public SignatureType Signature
    {
        get
        {
            return this.signatureField;
        }
        set
        {
            this.signatureField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "ID")]
    public string Id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.w3.org/2000/09/xmldsig#")]
public partial class SignatureType
{

    private SignedInfoType signedInfoField;

    private SignatureValueType signatureValueField;

    private KeyInfoType keyInfoField;

    private ObjectType[] objectField;

    private string idField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public SignedInfoType SignedInfo
    {
        get
        {
            return this.signedInfoField;
        }
        set
        {
            this.signedInfoField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
    public SignatureValueType SignatureValue
    {
        get
        {
            return this.signatureValueField;
        }
        set
        {
            this.signatureValueField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
    public KeyInfoType KeyInfo
    {
        get
        {
            return this.keyInfoField;
        }
        set
        {
            this.keyInfoField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Object", Order = 3)]
    public ObjectType[] Object
    {
        get
        {
            return this.objectField;
        }
        set
        {
            this.objectField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "ID")]
    public string Id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.w3.org/2000/09/xmldsig#")]
public partial class SignedInfoType
{

    private CanonicalizationMethodType canonicalizationMethodField;

    private SignatureMethodType signatureMethodField;

    private ReferenceType[] referenceField;

    private string idField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public CanonicalizationMethodType CanonicalizationMethod
    {
        get
        {
            return this.canonicalizationMethodField;
        }
        set
        {
            this.canonicalizationMethodField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
    public SignatureMethodType SignatureMethod
    {
        get
        {
            return this.signatureMethodField;
        }
        set
        {
            this.signatureMethodField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Reference", Order = 2)]
    public ReferenceType[] Reference
    {
        get
        {
            return this.referenceField;
        }
        set
        {
            this.referenceField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "ID")]
    public string Id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.w3.org/2000/09/xmldsig#")]
public partial class CanonicalizationMethodType
{

    private System.Xml.XmlNode[] anyField;

    private string algorithmField;

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    [System.Xml.Serialization.XmlAnyElementAttribute(Order = 0)]
    public System.Xml.XmlNode[] Any
    {
        get
        {
            return this.anyField;
        }
        set
        {
            this.anyField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "anyURI")]
    public string Algorithm
    {
        get
        {
            return this.algorithmField;
        }
        set
        {
            this.algorithmField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.w3.org/2000/09/xmldsig#")]
public partial class SignatureMethodType
{

    private string hMACOutputLengthField;

    private System.Xml.XmlNode[] anyField;

    private string algorithmField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "integer", Order = 0)]
    public string HMACOutputLength
    {
        get
        {
            return this.hMACOutputLengthField;
        }
        set
        {
            this.hMACOutputLengthField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    [System.Xml.Serialization.XmlAnyElementAttribute(Order = 1)]
    public System.Xml.XmlNode[] Any
    {
        get
        {
            return this.anyField;
        }
        set
        {
            this.anyField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "anyURI")]
    public string Algorithm
    {
        get
        {
            return this.algorithmField;
        }
        set
        {
            this.algorithmField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.w3.org/2000/09/xmldsig#")]
public partial class ReferenceType
{

    private TransformType[] transformsField;

    private DigestMethodType digestMethodField;

    private byte[] digestValueField;

    private string idField;

    private string uRIField;

    private string typeField;

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Order = 0)]
    [System.Xml.Serialization.XmlArrayItemAttribute("Transform", IsNullable = false)]
    public TransformType[] Transforms
    {
        get
        {
            return this.transformsField;
        }
        set
        {
            this.transformsField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
    public DigestMethodType DigestMethod
    {
        get
        {
            return this.digestMethodField;
        }
        set
        {
            this.digestMethodField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "base64Binary", Order = 2)]
    public byte[] DigestValue
    {
        get
        {
            return this.digestValueField;
        }
        set
        {
            this.digestValueField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "ID")]
    public string Id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "anyURI")]
    public string URI
    {
        get
        {
            return this.uRIField;
        }
        set
        {
            this.uRIField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "anyURI")]
    public string Type
    {
        get
        {
            return this.typeField;
        }
        set
        {
            this.typeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.w3.org/2000/09/xmldsig#")]
public partial class TransformType
{

    private object[] itemsField;

    private string[] textField;

    private string algorithmField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute(Order = 0)]
    [System.Xml.Serialization.XmlElementAttribute("XPath", typeof(string), Order = 0)]
    public object[] Items
    {
        get
        {
            return this.itemsField;
        }
        set
        {
            this.itemsField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text
    {
        get
        {
            return this.textField;
        }
        set
        {
            this.textField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "anyURI")]
    public string Algorithm
    {
        get
        {
            return this.algorithmField;
        }
        set
        {
            this.algorithmField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.w3.org/2000/09/xmldsig#")]
public partial class DigestMethodType
{

    private System.Xml.XmlNode[] anyField;

    private string algorithmField;

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    [System.Xml.Serialization.XmlAnyElementAttribute(Order = 0)]
    public System.Xml.XmlNode[] Any
    {
        get
        {
            return this.anyField;
        }
        set
        {
            this.anyField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "anyURI")]
    public string Algorithm
    {
        get
        {
            return this.algorithmField;
        }
        set
        {
            this.algorithmField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.w3.org/2000/09/xmldsig#")]
public partial class SignatureValueType
{

    private string idField;

    private byte[] valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "ID")]
    public string Id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute(DataType = "base64Binary")]
    public byte[] Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.w3.org/2000/09/xmldsig#")]
public partial class KeyInfoType
{

    private object[] itemsField;

    private ItemsChoiceType2[] itemsElementNameField;

    private string[] textField;

    private string idField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute(Order = 0)]
    [System.Xml.Serialization.XmlElementAttribute("KeyName", typeof(string), Order = 0)]
    [System.Xml.Serialization.XmlElementAttribute("KeyValue", typeof(KeyValueType), Order = 0)]
    [System.Xml.Serialization.XmlElementAttribute("MgmtData", typeof(string), Order = 0)]
    [System.Xml.Serialization.XmlElementAttribute("PGPData", typeof(PGPDataType), Order = 0)]
    [System.Xml.Serialization.XmlElementAttribute("RetrievalMethod", typeof(RetrievalMethodType), Order = 0)]
    [System.Xml.Serialization.XmlElementAttribute("SPKIData", typeof(SPKIDataType), Order = 0)]
    [System.Xml.Serialization.XmlElementAttribute("X509Data", typeof(X509DataType), Order = 0)]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
    public object[] Items
    {
        get
        {
            return this.itemsField;
        }
        set
        {
            this.itemsField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ItemsElementName", Order = 1)]
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemsChoiceType2[] ItemsElementName
    {
        get
        {
            return this.itemsElementNameField;
        }
        set
        {
            this.itemsElementNameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text
    {
        get
        {
            return this.textField;
        }
        set
        {
            this.textField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "ID")]
    public string Id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.w3.org/2000/09/xmldsig#")]
public partial class KeyValueType
{

    private object itemField;

    private string[] textField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute(Order = 0)]
    [System.Xml.Serialization.XmlElementAttribute("DSAKeyValue", typeof(DSAKeyValueType), Order = 0)]
    [System.Xml.Serialization.XmlElementAttribute("RSAKeyValue", typeof(RSAKeyValueType), Order = 0)]
    public object Item
    {
        get
        {
            return this.itemField;
        }
        set
        {
            this.itemField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text
    {
        get
        {
            return this.textField;
        }
        set
        {
            this.textField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.w3.org/2000/09/xmldsig#")]
public partial class DSAKeyValueType
{

    private byte[] pField;

    private byte[] qField;

    private byte[] gField;

    private byte[] yField;

    private byte[] jField;

    private byte[] seedField;

    private byte[] pgenCounterField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "base64Binary", Order = 0)]
    public byte[] P
    {
        get
        {
            return this.pField;
        }
        set
        {
            this.pField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "base64Binary", Order = 1)]
    public byte[] Q
    {
        get
        {
            return this.qField;
        }
        set
        {
            this.qField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "base64Binary", Order = 2)]
    public byte[] G
    {
        get
        {
            return this.gField;
        }
        set
        {
            this.gField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "base64Binary", Order = 3)]
    public byte[] Y
    {
        get
        {
            return this.yField;
        }
        set
        {
            this.yField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "base64Binary", Order = 4)]
    public byte[] J
    {
        get
        {
            return this.jField;
        }
        set
        {
            this.jField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "base64Binary", Order = 5)]
    public byte[] Seed
    {
        get
        {
            return this.seedField;
        }
        set
        {
            this.seedField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "base64Binary", Order = 6)]
    public byte[] PgenCounter
    {
        get
        {
            return this.pgenCounterField;
        }
        set
        {
            this.pgenCounterField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.w3.org/2000/09/xmldsig#")]
public partial class RSAKeyValueType
{

    private byte[] modulusField;

    private byte[] exponentField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "base64Binary", Order = 0)]
    public byte[] Modulus
    {
        get
        {
            return this.modulusField;
        }
        set
        {
            this.modulusField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "base64Binary", Order = 1)]
    public byte[] Exponent
    {
        get
        {
            return this.exponentField;
        }
        set
        {
            this.exponentField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.w3.org/2000/09/xmldsig#")]
public partial class PGPDataType
{

    private object[] itemsField;

    private ItemsChoiceType1[] itemsElementNameField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute(Order = 0)]
    [System.Xml.Serialization.XmlElementAttribute("PGPKeyID", typeof(byte[]), DataType = "base64Binary", Order = 0)]
    [System.Xml.Serialization.XmlElementAttribute("PGPKeyPacket", typeof(byte[]), DataType = "base64Binary", Order = 0)]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
    public object[] Items
    {
        get
        {
            return this.itemsField;
        }
        set
        {
            this.itemsField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ItemsElementName", Order = 1)]
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemsChoiceType1[] ItemsElementName
    {
        get
        {
            return this.itemsElementNameField;
        }
        set
        {
            this.itemsElementNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.w3.org/2000/09/xmldsig#", IncludeInSchema = false)]
public enum ItemsChoiceType1
{

    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("##any:")]
    Item,

    /// <remarks/>
    PGPKeyID,

    /// <remarks/>
    PGPKeyPacket,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.w3.org/2000/09/xmldsig#")]
public partial class RetrievalMethodType
{

    private TransformType[] transformsField;

    private string uRIField;

    private string typeField;

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Order = 0)]
    [System.Xml.Serialization.XmlArrayItemAttribute("Transform", IsNullable = false)]
    public TransformType[] Transforms
    {
        get
        {
            return this.transformsField;
        }
        set
        {
            this.transformsField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "anyURI")]
    public string URI
    {
        get
        {
            return this.uRIField;
        }
        set
        {
            this.uRIField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "anyURI")]
    public string Type
    {
        get
        {
            return this.typeField;
        }
        set
        {
            this.typeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.w3.org/2000/09/xmldsig#")]
public partial class SPKIDataType
{

    private object[] itemsField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute(Order = 0)]
    [System.Xml.Serialization.XmlElementAttribute("SPKISexp", typeof(byte[]), DataType = "base64Binary", Order = 0)]
    public object[] Items
    {
        get
        {
            return this.itemsField;
        }
        set
        {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.w3.org/2000/09/xmldsig#")]
public partial class X509DataType
{

    private object[] itemsField;

    private ItemsChoiceType[] itemsElementNameField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute(Order = 0)]
    [System.Xml.Serialization.XmlElementAttribute("X509CRL", typeof(byte[]), DataType = "base64Binary", Order = 0)]
    [System.Xml.Serialization.XmlElementAttribute("X509Certificate", typeof(byte[]), DataType = "base64Binary", Order = 0)]
    [System.Xml.Serialization.XmlElementAttribute("X509IssuerSerial", typeof(X509IssuerSerialType), Order = 0)]
    [System.Xml.Serialization.XmlElementAttribute("X509SKI", typeof(byte[]), DataType = "base64Binary", Order = 0)]
    [System.Xml.Serialization.XmlElementAttribute("X509SubjectName", typeof(string), Order = 0)]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
    public object[] Items
    {
        get
        {
            return this.itemsField;
        }
        set
        {
            this.itemsField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ItemsElementName", Order = 1)]
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemsChoiceType[] ItemsElementName
    {
        get
        {
            return this.itemsElementNameField;
        }
        set
        {
            this.itemsElementNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.w3.org/2000/09/xmldsig#")]
public partial class X509IssuerSerialType
{

    private string x509IssuerNameField;

    private string x509SerialNumberField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public string X509IssuerName
    {
        get
        {
            return this.x509IssuerNameField;
        }
        set
        {
            this.x509IssuerNameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "integer", Order = 1)]
    public string X509SerialNumber
    {
        get
        {
            return this.x509SerialNumberField;
        }
        set
        {
            this.x509SerialNumberField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.w3.org/2000/09/xmldsig#", IncludeInSchema = false)]
public enum ItemsChoiceType
{

    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("##any:")]
    Item,

    /// <remarks/>
    X509CRL,

    /// <remarks/>
    X509Certificate,

    /// <remarks/>
    X509IssuerSerial,

    /// <remarks/>
    X509SKI,

    /// <remarks/>
    X509SubjectName,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.w3.org/2000/09/xmldsig#", IncludeInSchema = false)]
public enum ItemsChoiceType2
{

    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("##any:")]
    Item,

    /// <remarks/>
    KeyName,

    /// <remarks/>
    KeyValue,

    /// <remarks/>
    MgmtData,

    /// <remarks/>
    PGPData,

    /// <remarks/>
    RetrievalMethod,

    /// <remarks/>
    SPKIData,

    /// <remarks/>
    X509Data,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.w3.org/2000/09/xmldsig#")]
public partial class ObjectType
{

    private System.Xml.XmlNode[] anyField;

    private string idField;

    private string mimeTypeField;

    private string encodingField;

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    [System.Xml.Serialization.XmlAnyElementAttribute(Order = 0)]
    public System.Xml.XmlNode[] Any
    {
        get
        {
            return this.anyField;
        }
        set
        {
            this.anyField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "ID")]
    public string Id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string MimeType
    {
        get
        {
            return this.mimeTypeField;
        }
        set
        {
            this.mimeTypeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "anyURI")]
    public string Encoding
    {
        get
        {
            return this.encodingField;
        }
        set
        {
            this.encodingField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://minameddelanden.gov.se/schema/Message")]
public partial class DistributionStatus
{

    private string recipientIdField;

    private DistributionTypes typeField;

    private DeliveryStatus deliveryStatusField;

    private bool deliveryStatusFieldSpecified;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public string RecipientId
    {
        get
        {
            return this.recipientIdField;
        }
        set
        {
            this.recipientIdField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
    public DistributionTypes Type
    {
        get
        {
            return this.typeField;
        }
        set
        {
            this.typeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
    public DeliveryStatus DeliveryStatus
    {
        get
        {
            return this.deliveryStatusField;
        }
        set
        {
            this.deliveryStatusField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DeliveryStatusSpecified
    {
        get
        {
            return this.deliveryStatusFieldSpecified;
        }
        set
        {
            this.deliveryStatusFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://minameddelanden.gov.se/schema/Message")]
public enum DistributionTypes
{

    /// <remarks/>
    Digital,

    /// <remarks/>
    Paper,

    /// <remarks/>
    Not,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://minameddelanden.gov.se/schema/Message")]
public enum DeliveryStatus
{

    /// <remarks/>
    Delivered,

    /// <remarks/>
    Pending,

    /// <remarks/>
    DeliveryFailed,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://minameddelanden.gov.se/schema/Message")]
public partial class SupportInfo
{

    private string textField;

    private string logoField;

    private string uRLField;

    private string phoneNumberField;

    private string emailAdressField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public string Text
    {
        get
        {
            return this.textField;
        }
        set
        {
            this.textField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "anyURI", Order = 1)]
    public string Logo
    {
        get
        {
            return this.logoField;
        }
        set
        {
            this.logoField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "anyURI", Order = 2)]
    public string URL
    {
        get
        {
            return this.uRLField;
        }
        set
        {
            this.uRLField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
    public string PhoneNumber
    {
        get
        {
            return this.phoneNumberField;
        }
        set
        {
            this.phoneNumberField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
    public string EmailAdress
    {
        get
        {
            return this.emailAdressField;
        }
        set
        {
            this.emailAdressField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://minameddelanden.gov.se/schema/Message")]
public partial class MessageHeader
{

    private string idField;

    private string subjectField;

    private SupportInfo supportinfoField;

    private MetaData[] metadataField;

    private string languageField;

    private ReplyOptions replyField;

    private bool replyFieldSpecified;

    private ReceiptOptions receiptRequestField;

    private bool receiptRequestFieldSpecified;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public string Id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
    public string Subject
    {
        get
        {
            return this.subjectField;
        }
        set
        {
            this.subjectField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
    public SupportInfo Supportinfo
    {
        get
        {
            return this.supportinfoField;
        }
        set
        {
            this.supportinfoField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Metadata", Order = 3)]
    public MetaData[] Metadata
    {
        get
        {
            return this.metadataField;
        }
        set
        {
            this.metadataField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "language", Order = 4)]
    public string Language
    {
        get
        {
            return this.languageField;
        }
        set
        {
            this.languageField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
    public ReplyOptions Reply
    {
        get
        {
            return this.replyField;
        }
        set
        {
            this.replyField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ReplySpecified
    {
        get
        {
            return this.replyFieldSpecified;
        }
        set
        {
            this.replyFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
    public ReceiptOptions ReceiptRequest
    {
        get
        {
            return this.receiptRequestField;
        }
        set
        {
            this.receiptRequestField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ReceiptRequestSpecified
    {
        get
        {
            return this.receiptRequestFieldSpecified;
        }
        set
        {
            this.receiptRequestFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://minameddelanden.gov.se/schema/Message")]
public partial class SecureMessage
{

    private MessageHeader headerField;

    private MessageBody bodyField;

    private Attachment[] attachmentField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public MessageHeader Header
    {
        get
        {
            return this.headerField;
        }
        set
        {
            this.headerField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
    public MessageBody Body
    {
        get
        {
            return this.bodyField;
        }
        set
        {
            this.bodyField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Attachment", Order = 2)]
    public Attachment[] Attachment
    {
        get
        {
            return this.attachmentField;
        }
        set
        {
            this.attachmentField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName = "distributeSecure", WrapperNamespace = "http://minameddelanden.gov.se/schema/Message/v2", IsWrapped = true)]
public partial class distributeSecureRequest
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://minameddelanden.gov.se/schema/Message/v2", Order = 0)]
    public SignedDelivery signedDelivery;

    public distributeSecureRequest()
    {
    }

    public distributeSecureRequest(SignedDelivery signedDelivery)
    {
        this.signedDelivery = signedDelivery;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName = "distributeSecureResponse", WrapperNamespace = "http://minameddelanden.gov.se/Message", IsWrapped = true)]
public partial class distributeSecureResponse
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://minameddelanden.gov.se/Message", Order = 0)]
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string @return;

    public distributeSecureResponse()
    {
    }

    public distributeSecureResponse(string @return)
    {
        this.@return = @return;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName = "checkDistributionStatus", WrapperNamespace = "http://minameddelanden.gov.se/Message", IsWrapped = true)]
public partial class checkDistributionStatusRequest
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://minameddelanden.gov.se/Message", Order = 0)]
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string arg0;

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://minameddelanden.gov.se/Message", Order = 1)]
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string arg1;

    public checkDistributionStatusRequest()
    {
    }

    public checkDistributionStatusRequest(string arg0, string arg1)
    {
        this.arg0 = arg0;
        this.arg1 = arg1;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName = "checkDistributionStatusResponse", WrapperNamespace = "http://minameddelanden.gov.se/Message", IsWrapped = true)]
public partial class checkDistributionStatusResponse
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://minameddelanden.gov.se/Message", Order = 0)]
    [System.Xml.Serialization.XmlElementAttribute("return", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public DistributionStatus[] @return;

    public checkDistributionStatusResponse()
    {
    }

    public checkDistributionStatusResponse(DistributionStatus[] @return)
    {
        this.@return = @return;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface MessagePortv2Channel : MessagePortv2, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class MessagePortv2Client : System.ServiceModel.ClientBase<MessagePortv2>, MessagePortv2
{

    public MessagePortv2Client()
    {
    }

    public MessagePortv2Client(string endpointConfigurationName) :
            base(endpointConfigurationName)
    {
    }

    public MessagePortv2Client(string endpointConfigurationName, string remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
    {
    }

    public MessagePortv2Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
    {
    }

    public MessagePortv2Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
    {
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    distributeSecureResponse MessagePortv2.distributeSecure(distributeSecureRequest request)
    {
        return base.Channel.distributeSecure(request);
    }

    public string distributeSecure(SignedDelivery signedDelivery)
    {
        distributeSecureRequest inValue = new distributeSecureRequest();
        inValue.signedDelivery = signedDelivery;
        distributeSecureResponse retVal = ((MessagePortv2)(this)).distributeSecure(inValue);
        return retVal.@return;
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<distributeSecureResponse> MessagePortv2.distributeSecureAsync(distributeSecureRequest request)
    {
        return base.Channel.distributeSecureAsync(request);
    }

    public System.Threading.Tasks.Task<distributeSecureResponse> distributeSecureAsync(SignedDelivery signedDelivery)
    {
        distributeSecureRequest inValue = new distributeSecureRequest();
        inValue.signedDelivery = signedDelivery;
        return ((MessagePortv2)(this)).distributeSecureAsync(inValue);
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    checkDistributionStatusResponse MessagePortv2.checkDistributionStatus(checkDistributionStatusRequest request)
    {
        return base.Channel.checkDistributionStatus(request);
    }

    public DistributionStatus[] checkDistributionStatus(string arg0, string arg1)
    {
        checkDistributionStatusRequest inValue = new checkDistributionStatusRequest();
        inValue.arg0 = arg0;
        inValue.arg1 = arg1;
        checkDistributionStatusResponse retVal = ((MessagePortv2)(this)).checkDistributionStatus(inValue);
        return retVal.@return;
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<checkDistributionStatusResponse> MessagePortv2.checkDistributionStatusAsync(checkDistributionStatusRequest request)
    {
        return base.Channel.checkDistributionStatusAsync(request);
    }

    public System.Threading.Tasks.Task<checkDistributionStatusResponse> checkDistributionStatusAsync(string arg0, string arg1)
    {
        checkDistributionStatusRequest inValue = new checkDistributionStatusRequest();
        inValue.arg0 = arg0;
        inValue.arg1 = arg1;
        return ((MessagePortv2)(this)).checkDistributionStatusAsync(inValue);
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Name = "MessagePort-v3", Namespace = "http://minameddelanden.gov.se/Message", ConfigurationName = "MessagePortv3")]
public interface MessagePortv3
{

    // CODEGEN: Meddelandekontrakt genereras eftersom omslutningsnamnområde (wrapper) (http://minameddelanden.gov.se/schema/Message/v3) i meddelande distributeSecureRequest inte matchar standardvärdet (http://minameddelanden.gov.se/Message)
    [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
    [System.ServiceModel.FaultContractAttribute(typeof(minameddelanden.gov.se.schema.Common.v3.ExceptionInformation), Action = "", Name = "applicationFault", Namespace = "http://minameddelanden.gov.se/schema/Common/v3")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    distributeSecureResponse1 distributeSecure(distributeSecureRequest1 request);

    [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
    System.Threading.Tasks.Task<distributeSecureResponse1> distributeSecureAsync(distributeSecureRequest1 request);

    // CODEGEN: Meddelandekontrakt genereras eftersom omslutningsnamnområde (wrapper) (http://minameddelanden.gov.se/schema/Message/v3) i meddelande checkDistributionStatusRequest inte matchar standardvärdet (http://minameddelanden.gov.se/Message)
    [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
    [System.ServiceModel.FaultContractAttribute(typeof(minameddelanden.gov.se.schema.Common.v3.ExceptionInformation), Action = "", Name = "applicationFault", Namespace = "http://minameddelanden.gov.se/schema/Common/v3")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    checkDistributionStatusResponse1 checkDistributionStatus(checkDistributionStatusRequest1 request);

    [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
    System.Threading.Tasks.Task<checkDistributionStatusResponse1> checkDistributionStatusAsync(checkDistributionStatusRequest1 request);
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName = "distributeSecure", WrapperNamespace = "http://minameddelanden.gov.se/schema/Message/v3", IsWrapped = true)]
public partial class distributeSecureRequest1
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://minameddelanden.gov.se/schema/Message/v3", Order = 0)]
    public SignedDelivery1 signedDelivery;

    public distributeSecureRequest1()
    {
    }

    public distributeSecureRequest1(SignedDelivery1 signedDelivery)
    {
        this.signedDelivery = signedDelivery;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName = "distributeSecureResponse", WrapperNamespace = "http://minameddelanden.gov.se/schema/Message/v3", IsWrapped = true)]
public partial class distributeSecureResponse1
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://minameddelanden.gov.se/schema/Message/v3", Order = 0)]
    public string @return;

    public distributeSecureResponse1()
    {
    }

    public distributeSecureResponse1(string @return)
    {
        this.@return = @return;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName = "checkDistributionStatus", WrapperNamespace = "http://minameddelanden.gov.se/schema/Message/v3", IsWrapped = true)]
public partial class checkDistributionStatusRequest1
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://minameddelanden.gov.se/schema/Message/v3", Order = 0)]
    public string senderId;

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://minameddelanden.gov.se/schema/Message/v3", Order = 1)]
    public string distributionId;

    public checkDistributionStatusRequest1()
    {
    }

    public checkDistributionStatusRequest1(string senderId, string distributionId)
    {
        this.senderId = senderId;
        this.distributionId = distributionId;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName = "checkDistributionStatusResponse", WrapperNamespace = "http://minameddelanden.gov.se/schema/Message/v3", IsWrapped = true)]
public partial class checkDistributionStatusResponse1
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://minameddelanden.gov.se/schema/Message/v3", Order = 0)]
    [System.Xml.Serialization.XmlElementAttribute("return")]
    public DistributionStatus[] @return;

    public checkDistributionStatusResponse1()
    {
    }

    public checkDistributionStatusResponse1(DistributionStatus[] @return)
    {
        this.@return = @return;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface MessagePortv3Channel : MessagePortv3, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class MessagePortv3Client : System.ServiceModel.ClientBase<MessagePortv3>, MessagePortv3
{

    public MessagePortv3Client()
    {
    }

    public MessagePortv3Client(string endpointConfigurationName) :
            base(endpointConfigurationName)
    {
    }

    public MessagePortv3Client(string endpointConfigurationName, string remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
    {
    }

    public MessagePortv3Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
    {
    }

    public MessagePortv3Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
    {
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    distributeSecureResponse1 MessagePortv3.distributeSecure(distributeSecureRequest1 request)
    {
        return base.Channel.distributeSecure(request);
    }

    public string distributeSecure(SignedDelivery1 signedDelivery)
    {
        distributeSecureRequest1 inValue = new distributeSecureRequest1();
        inValue.signedDelivery = signedDelivery;
        distributeSecureResponse1 retVal = ((MessagePortv3)(this)).distributeSecure(inValue);
        return retVal.@return;
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<distributeSecureResponse1> MessagePortv3.distributeSecureAsync(distributeSecureRequest1 request)
    {
        return base.Channel.distributeSecureAsync(request);
    }

    public System.Threading.Tasks.Task<distributeSecureResponse1> distributeSecureAsync(SignedDelivery1 signedDelivery)
    {
        distributeSecureRequest1 inValue = new distributeSecureRequest1();
        inValue.signedDelivery = signedDelivery;
        return ((MessagePortv3)(this)).distributeSecureAsync(inValue);
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    checkDistributionStatusResponse1 MessagePortv3.checkDistributionStatus(checkDistributionStatusRequest1 request)
    {
        return base.Channel.checkDistributionStatus(request);
    }

    public DistributionStatus[] checkDistributionStatus(string senderId, string distributionId)
    {
        checkDistributionStatusRequest1 inValue = new checkDistributionStatusRequest1();
        inValue.senderId = senderId;
        inValue.distributionId = distributionId;
        checkDistributionStatusResponse1 retVal = ((MessagePortv3)(this)).checkDistributionStatus(inValue);
        return retVal.@return;
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<checkDistributionStatusResponse1> MessagePortv3.checkDistributionStatusAsync(checkDistributionStatusRequest1 request)
    {
        return base.Channel.checkDistributionStatusAsync(request);
    }

    public System.Threading.Tasks.Task<checkDistributionStatusResponse1> checkDistributionStatusAsync(string senderId, string distributionId)
    {
        checkDistributionStatusRequest1 inValue = new checkDistributionStatusRequest1();
        inValue.senderId = senderId;
        inValue.distributionId = distributionId;
        return ((MessagePortv3)(this)).checkDistributionStatusAsync(inValue);
    }
}
namespace minameddelanden.gov.se.schema.Common
{
    using System.Runtime.Serialization;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ExceptionInformation", Namespace = "http://minameddelanden.gov.se/schema/Common")]
    public partial class ExceptionInformation : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private int ErrorCodeField;

        private string DescriptionField;

        private string CallIdField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public int ErrorCode
        {
            get
            {
                return this.ErrorCodeField;
            }
            set
            {
                this.ErrorCodeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, EmitDefaultValue = false, Order = 1)]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, EmitDefaultValue = false, Order = 2)]
        public string CallId
        {
            get
            {
                return this.CallIdField;
            }
            set
            {
                this.CallIdField = value;
            }
        }
    }
}
namespace minameddelanden.gov.se.schema.Common.v3
{
    using System.Runtime.Serialization;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ExceptionInformation", Namespace = "http://minameddelanden.gov.se/schema/Common/v3")]
    public partial class ExceptionInformation : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private int ErrorCodeField;

        private string DescriptionField;

        private string CallIdField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public int ErrorCode
        {
            get
            {
                return this.ErrorCodeField;
            }
            set
            {
                this.ErrorCodeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, EmitDefaultValue = false, Order = 1)]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, EmitDefaultValue = false, Order = 2)]
        public string CallId
        {
            get
            {
                return this.CallIdField;
            }
            set
            {
                this.CallIdField = value;
            }
        }
    }
}
