//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SE.GOV.MM.Integration.Package.DataLayer.DeliveryMailbox {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestBase", Namespace="https://SE.GOV.MM.Integration.DeliveryMailbox/2015/04")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SE.GOV.MM.Integration.Package.DataLayer.DeliveryMailbox.SendPackageToMailboxRequest))]
    public partial class RequestBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SendPackageToMailboxRequest", Namespace="http://schemas.datacontract.org/2004/07/SE.GOV.MM.Integration.DeliveryMailbox.Dat" +
        "aTransferObject.Request")]
    [System.SerializableAttribute()]
    public partial class SendPackageToMailboxRequest : SE.GOV.MM.Integration.Package.DataLayer.DeliveryMailbox.RequestBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SE.GOV.MM.Integration.Package.DataLayer.DeliveryMailbox.Mail MailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SE.GOV.MM.Integration.Package.DataLayer.DeliveryMailbox.Mailbox MailboxField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SE.GOV.MM.Integration.Package.DataLayer.DeliveryMailbox.Mail Mail {
            get {
                return this.MailField;
            }
            set {
                if ((object.ReferenceEquals(this.MailField, value) != true)) {
                    this.MailField = value;
                    this.RaisePropertyChanged("Mail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SE.GOV.MM.Integration.Package.DataLayer.DeliveryMailbox.Mailbox Mailbox {
            get {
                return this.MailboxField;
            }
            set {
                if ((object.ReferenceEquals(this.MailboxField, value) != true)) {
                    this.MailboxField = value;
                    this.RaisePropertyChanged("Mailbox");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Mail", Namespace="https://SE.GOV.MM.Integration.DeliveryMailbox/2015/04")]
    [System.SerializableAttribute()]
    public partial class Mail : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SE.GOV.MM.Integration.Package.DataLayer.DeliveryMailbox.Attachment[] AttachmentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SE.GOV.MM.Integration.Package.DataLayer.DeliveryMailbox.Body BodyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CertificationBySubjectNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorrealationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageHeaderIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SE.GOV.MM.Integration.Package.DataLayer.DeliveryMailbox.MetaData[] MetaDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SE.GOV.MM.Integration.Package.DataLayer.DeliveryMailbox.Recipient RecipientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenderOrgNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenderOrgNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubjectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SupInfoEmailAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SupInfoPhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SupInfoTextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SupInfoUrIField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SE.GOV.MM.Integration.Package.DataLayer.DeliveryMailbox.Attachment[] Attachments {
            get {
                return this.AttachmentsField;
            }
            set {
                if ((object.ReferenceEquals(this.AttachmentsField, value) != true)) {
                    this.AttachmentsField = value;
                    this.RaisePropertyChanged("Attachments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SE.GOV.MM.Integration.Package.DataLayer.DeliveryMailbox.Body Body {
            get {
                return this.BodyField;
            }
            set {
                if ((object.ReferenceEquals(this.BodyField, value) != true)) {
                    this.BodyField = value;
                    this.RaisePropertyChanged("Body");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CertificationBySubjectName {
            get {
                return this.CertificationBySubjectNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CertificationBySubjectNameField, value) != true)) {
                    this.CertificationBySubjectNameField = value;
                    this.RaisePropertyChanged("CertificationBySubjectName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CorrealationId {
            get {
                return this.CorrealationIdField;
            }
            set {
                if ((object.ReferenceEquals(this.CorrealationIdField, value) != true)) {
                    this.CorrealationIdField = value;
                    this.RaisePropertyChanged("CorrealationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageHeaderId {
            get {
                return this.MessageHeaderIdField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageHeaderIdField, value) != true)) {
                    this.MessageHeaderIdField = value;
                    this.RaisePropertyChanged("MessageHeaderId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SE.GOV.MM.Integration.Package.DataLayer.DeliveryMailbox.MetaData[] MetaData {
            get {
                return this.MetaDataField;
            }
            set {
                if ((object.ReferenceEquals(this.MetaDataField, value) != true)) {
                    this.MetaDataField = value;
                    this.RaisePropertyChanged("MetaData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SE.GOV.MM.Integration.Package.DataLayer.DeliveryMailbox.Recipient Recipient {
            get {
                return this.RecipientField;
            }
            set {
                if ((object.ReferenceEquals(this.RecipientField, value) != true)) {
                    this.RecipientField = value;
                    this.RaisePropertyChanged("Recipient");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Reference {
            get {
                return this.ReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.ReferenceField, value) != true)) {
                    this.ReferenceField = value;
                    this.RaisePropertyChanged("Reference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sender {
            get {
                return this.SenderField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderField, value) != true)) {
                    this.SenderField = value;
                    this.RaisePropertyChanged("Sender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SenderOrgName {
            get {
                return this.SenderOrgNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderOrgNameField, value) != true)) {
                    this.SenderOrgNameField = value;
                    this.RaisePropertyChanged("SenderOrgName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SenderOrgNumber {
            get {
                return this.SenderOrgNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderOrgNumberField, value) != true)) {
                    this.SenderOrgNumberField = value;
                    this.RaisePropertyChanged("SenderOrgNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Subject {
            get {
                return this.SubjectField;
            }
            set {
                if ((object.ReferenceEquals(this.SubjectField, value) != true)) {
                    this.SubjectField = value;
                    this.RaisePropertyChanged("Subject");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SupInfoEmailAddress {
            get {
                return this.SupInfoEmailAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.SupInfoEmailAddressField, value) != true)) {
                    this.SupInfoEmailAddressField = value;
                    this.RaisePropertyChanged("SupInfoEmailAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SupInfoPhoneNumber {
            get {
                return this.SupInfoPhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.SupInfoPhoneNumberField, value) != true)) {
                    this.SupInfoPhoneNumberField = value;
                    this.RaisePropertyChanged("SupInfoPhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SupInfoText {
            get {
                return this.SupInfoTextField;
            }
            set {
                if ((object.ReferenceEquals(this.SupInfoTextField, value) != true)) {
                    this.SupInfoTextField = value;
                    this.RaisePropertyChanged("SupInfoText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SupInfoUrI {
            get {
                return this.SupInfoUrIField;
            }
            set {
                if ((object.ReferenceEquals(this.SupInfoUrIField, value) != true)) {
                    this.SupInfoUrIField = value;
                    this.RaisePropertyChanged("SupInfoUrI");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Mailbox", Namespace="https://SE.GOV.MM.Integration.DeliveryMailbox/2015/04")]
    [System.SerializableAttribute()]
    public partial class Mailbox : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LogoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServiceAdressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UIAdressField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Logo {
            get {
                return this.LogoField;
            }
            set {
                if ((object.ReferenceEquals(this.LogoField, value) != true)) {
                    this.LogoField = value;
                    this.RaisePropertyChanged("Logo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceAdress {
            get {
                return this.ServiceAdressField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceAdressField, value) != true)) {
                    this.ServiceAdressField = value;
                    this.RaisePropertyChanged("ServiceAdress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UIAdress {
            get {
                return this.UIAdressField;
            }
            set {
                if ((object.ReferenceEquals(this.UIAdressField, value) != true)) {
                    this.UIAdressField = value;
                    this.RaisePropertyChanged("UIAdress");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Body", Namespace="https://SE.GOV.MM.Integration.DeliveryMailbox/2015/04")]
    [System.SerializableAttribute()]
    public partial class Body : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContentType {
            get {
                return this.ContentTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentTypeField, value) != true)) {
                    this.ContentTypeField = value;
                    this.RaisePropertyChanged("ContentType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Text {
            get {
                return this.TextField;
            }
            set {
                if ((object.ReferenceEquals(this.TextField, value) != true)) {
                    this.TextField = value;
                    this.RaisePropertyChanged("Text");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Recipient", Namespace="https://SE.GOV.MM.Integration.DeliveryMailbox/2015/04")]
    [System.SerializableAttribute()]
    public partial class Recipient : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ToField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string To {
            get {
                return this.ToField;
            }
            set {
                if ((object.ReferenceEquals(this.ToField, value) != true)) {
                    this.ToField = value;
                    this.RaisePropertyChanged("To");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Attachment", Namespace="https://SE.GOV.MM.Integration.DeliveryMailbox/2015/04")]
    [System.SerializableAttribute()]
    public partial class Attachment : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] BodyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FilenameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Body {
            get {
                return this.BodyField;
            }
            set {
                if ((object.ReferenceEquals(this.BodyField, value) != true)) {
                    this.BodyField = value;
                    this.RaisePropertyChanged("Body");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContentType {
            get {
                return this.ContentTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentTypeField, value) != true)) {
                    this.ContentTypeField = value;
                    this.RaisePropertyChanged("ContentType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Filename {
            get {
                return this.FilenameField;
            }
            set {
                if ((object.ReferenceEquals(this.FilenameField, value) != true)) {
                    this.FilenameField = value;
                    this.RaisePropertyChanged("Filename");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MetaData", Namespace="https://SE.GOV.MM.Integration.DeliveryMailbox/2015/04")]
    [System.SerializableAttribute()]
    public partial class MetaData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key {
            get {
                return this.KeyField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyField, value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseBase", Namespace="https://SE.GOV.MM.Integration.DeliveryMailbox/2015/04")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SE.GOV.MM.Integration.Package.DataLayer.DeliveryMailbox.SendPackageToMailboxResponse))]
    public partial class ResponseBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SendPackageToMailboxResponse", Namespace="http://schemas.datacontract.org/2004/07/SE.GOV.MM.Integration.DeliveryMailbox.Dat" +
        "aTransferObject.Response")]
    [System.SerializableAttribute()]
    public partial class SendPackageToMailboxResponse : SE.GOV.MM.Integration.Package.DataLayer.DeliveryMailbox.ResponseBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool DeliveredField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RecipientIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Delivered {
            get {
                return this.DeliveredField;
            }
            set {
                if ((this.DeliveredField.Equals(value) != true)) {
                    this.DeliveredField = value;
                    this.RaisePropertyChanged("Delivered");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RecipientId {
            get {
                return this.RecipientIdField;
            }
            set {
                if ((object.ReferenceEquals(this.RecipientIdField, value) != true)) {
                    this.RecipientIdField = value;
                    this.RaisePropertyChanged("RecipientId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransId {
            get {
                return this.TransIdField;
            }
            set {
                if ((object.ReferenceEquals(this.TransIdField, value) != true)) {
                    this.TransIdField = value;
                    this.RaisePropertyChanged("TransId");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://SE.GOV.MM.Integration.DeliveryMailbox/2015/12", ConfigurationName="DeliveryMailbox.IDeliveryMailbox")]
    public interface IDeliveryMailbox {
        
        [System.ServiceModel.OperationContractAttribute(Action="https://SE.GOV.MM.Integration.DeliveryMailbox/2015/12/IDeliveryMailbox/SendPackag" +
            "eToMailbox", ReplyAction="https://SE.GOV.MM.Integration.DeliveryMailbox/2015/12/IDeliveryMailbox/SendPackag" +
            "eToMailboxResponse")]
        SE.GOV.MM.Integration.Package.DataLayer.DeliveryMailbox.SendPackageToMailboxResponse SendPackageToMailbox(SE.GOV.MM.Integration.Package.DataLayer.DeliveryMailbox.SendPackageToMailboxRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://SE.GOV.MM.Integration.DeliveryMailbox/2015/12/IDeliveryMailbox/SendPackag" +
            "eToMailbox", ReplyAction="https://SE.GOV.MM.Integration.DeliveryMailbox/2015/12/IDeliveryMailbox/SendPackag" +
            "eToMailboxResponse")]
        System.Threading.Tasks.Task<SE.GOV.MM.Integration.Package.DataLayer.DeliveryMailbox.SendPackageToMailboxResponse> SendPackageToMailboxAsync(SE.GOV.MM.Integration.Package.DataLayer.DeliveryMailbox.SendPackageToMailboxRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDeliveryMailboxChannel : SE.GOV.MM.Integration.Package.DataLayer.DeliveryMailbox.IDeliveryMailbox, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DeliveryMailboxClient : System.ServiceModel.ClientBase<SE.GOV.MM.Integration.Package.DataLayer.DeliveryMailbox.IDeliveryMailbox>, SE.GOV.MM.Integration.Package.DataLayer.DeliveryMailbox.IDeliveryMailbox {
        
        public DeliveryMailboxClient() {
        }
        
        public DeliveryMailboxClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DeliveryMailboxClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DeliveryMailboxClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DeliveryMailboxClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SE.GOV.MM.Integration.Package.DataLayer.DeliveryMailbox.SendPackageToMailboxResponse SendPackageToMailbox(SE.GOV.MM.Integration.Package.DataLayer.DeliveryMailbox.SendPackageToMailboxRequest request) {
            return base.Channel.SendPackageToMailbox(request);
        }
        
        public System.Threading.Tasks.Task<SE.GOV.MM.Integration.Package.DataLayer.DeliveryMailbox.SendPackageToMailboxResponse> SendPackageToMailboxAsync(SE.GOV.MM.Integration.Package.DataLayer.DeliveryMailbox.SendPackageToMailboxRequest request) {
            return base.Channel.SendPackageToMailboxAsync(request);
        }
    }
}
